[libraries]

log4jApi = 'org.apache.logging.log4j:log4j-api:2.17.1'
log4jCore = 'org.apache.logging.log4j:log4j-core:2.17.1'
commonsLang = 'org.apache.commons:commons-lang3:3.12.0'
commonsCli = 'commons-cli:commons-cli:1.1'
guava = 'com.google.guava:guava:19.0'
junit = 'junit:junit:4.12'
mockito = 'org.mockito:mockito-core:2.28.2'
assertj = 'org.assertj:assertj-core:3.6.2'
easymock = 'org.easymock:easymock:2.4'
easymockclassext = 'org.easymock:easymockclassextension:2.4'
jacksonDatabind = 'com.fasterxml.jackson.core:jackson-databind:2.13.4'
jacksonCore = 'com.fasterxml.jackson.core:jackson-core:2.13.4'
jacksonAnnotations = 'com.fasterxml.jackson.core:jackson-annotations:2.13.4'
jsr305 = 'com.google.code.findbugs:jsr305:1.3.9'
servletApi = 'javax.servlet:javax.servlet-api:3.1.0'
commonsIo = 'commons-io:commons-io:2.6'
springBeans = 'org.springframework:spring-beans:5.3.19'
springContext = 'org.springframework:spring-context:5.3.19'
springCore = 'org.springframework:spring-core:5.3.19'
springJdbc = 'org.springframework:spring-jdbc:5.3.19'
springTest = 'org.springframework:spring-test:5.3.19'
springWeb = 'org.springframework:spring-web:5.3.19'
springWebmvc = 'org.springframework:spring-webmvc:5.3.19'
ant = 'org.apache.ant:ant:1.8.2'
svnkit = 'org.tmatesoft.svnkit:svnkit:1.8.5'
tomcatElApi = 'org.apache.tomcat:tomcat-el-api:7.0.109'
tomcatJasperEl = 'org.apache.tomcat:tomcat-jasper-el:7.0.109'
tomcatJspApi = 'org.apache.tomcat:tomcat-jsp-api:7.0.109'
tomcatServletApi = 'org.apache.tomcat:tomcat-servlet-api:7.0.109'
annotationApi = 'javax.annotation:javax.annotation-api:1.3.2'